require("dotenv").config();
let mongoose = require("mongoose");
const Products = require("../models/Products");

mongoose
  .connect(process.env.DATABASE, {
    useNewUrlParser: true,
    useFindAndModify: true,
    useUnifiedTopology: true,
  })
  .then(() => console.log("DB Connection success"))
  .catch((err) => {
    console.error("Mongo connection error, ", err);
  });

let productseed = [
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
  },
  {
    name: "Apple",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "6-8 weeks maximum",
    freezerExpiry: "10-12 months",
  },
  {
    name: "Ketchup",
    isFresh: false,
    canRefrigerate: true,
    canFreeze: false,
    standardShelfLife: "180",
    fridgeExpiry: "6 months once opened",
  },
  {
    name: "Barbeque Sauce",
    isFresh: false,
    canRefrigerate: true,
    canFreeze: false,
    standardShelfLife: "4",
    fridgeExpiry: "6 months once opened",
  },
  {
    name: "Pineapple",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "3",
    fridgeExpiry: "2-3 days",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Lemon",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "8",
    fridgeExpiry: "3-5 days once cut",
    freezerExpiry: "3-4 months",
  },
  {
    name: "Grapefruit",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "28",
    fridgeExpiry: "6 weeks uncut",
    freezerExpiry: "3-4 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
  {
    name: "Banana",
    isFresh: true,
    canRefrigerate: true,
    canFreeze: true,
    standardShelfLife: "4",
    fridgeExpiry: "3-4 days once ripe",
    freezerExpiry: "2-3 months",
  },
];

Products.deleteMany({})
  .then(() => Products.insertMany(productseed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
